// Contenido del Congreso EHU-ULEAM 2026 — usado por V1 actualizada.
// Solo español (la nueva info es ES).

const CONTENT_EHU = {
  eventShort: "CIIIES 2026",
  eventFull: "Congreso Internacional sobre Innovación educativa, inclusión y sostenibilidad en Educación Superior",
  subtitle: "Intercambio de experiencias",
  tagline: "Educación y sostenibilidad — un diálogo entre la EHU, ULEAM, Colombia y Chile",
  dates: "28, 29 y 30 de Octubre 2026",
  location: "Facultad de Educación de Bilbao (EHU) · ULEAM (Ecuador)",
  hybrid: "Formato online y presencial · doble sede",
  nav: {
    presentacion: "Presentación",
    destinatarios: "Destinatarios",
    propuestas: "Envío de propuestas",
    programa: "Programa",
    publicacion: "Publicación",
    contacto: "Contacto",
  },
  heroLead:
    "Tres días de comunicaciones, pósters y simposios sobre innovación educativa, inclusión, sostenibilidad y los Objetivos de Desarrollo Sostenible en la Educación Superior, con doble sede en Bilbao y Manabí.",
  ctas: {
    submit: "Enviar propuesta",
    program: "Ver programa",
    download: "Descargar plantilla",
  },
  stats: [
    { n: "3", l: "Días de congreso" },
    { n: "2", l: "Sedes presenciales" },
    { n: "4", l: "Países participantes" },
    { n: "3", l: "Idiomas aceptados" },
  ],
  presentacion: {
    title: "Sobre el congreso",
    lead: "El congreso internacional “Educación y Sostenibilidad” crea un entorno en el que educadores y estudiantes de Ecuador y la Universidad del País Vasco (EHU) pueden compartir vivencias y aprender unos de otros.",
    objetivos: [
      { id: "01", title: "Intercambio cultural internacional", desc: "Facilitar la comprensión de los distintos enfoques educativos y de sostenibilidad en ambos países." },
      { id: "02", title: "Fortalecer habilidades nuevas", desc: "Proporcionar estrategias y metodologías que integren la sostenibilidad en los procesos de enseñanza." },
      { id: "03", title: "Iniciativas colaborativas", desc: "Motivar a los participantes a trabajar juntos en proyectos que aborden retos medioambientales locales y globales." },
      { id: "04", title: "Conciencia ambiental", desc: "Destacar la relevancia de formar en temas ecológicos y su impacto en la comunidad." },
      { id: "05", title: "Red de colaboración", desc: "Conectar a educadores y estudiantes con un compromiso compartido con la sostenibilidad y el aprendizaje continuo." },
    ],
  },
  destinatarios: {
    title: "Público (Dirigido a)",
    lead: "Profesorado y alumnado universitario interesado en la innovación educativa.",
    items: [
      "Docentes e investigadores/as de universidades de España, Ecuador y universidades internacionales colaboradoras",
      "Alumnado de grado y posgrado en proyectos de innovación docente",
      "Profesionales del ámbito escolar y de la Educación Social",
      "Responsables de practicum, TFG, TFM y Tesis Doctorales",
    ],
  },
  lineas: {
    title: "Líneas temáticas",
    lead: "Tres líneas para presentar trabajos en formato científico.",
    items: [
      { id: "01", title: "Trabajos teóricos o revisiones", desc: "Sobre temáticas relacionadas con educación y sostenibilidad en la Educación Superior." },
      { id: "02", title: "Experiencias prácticas de innovación", desc: "Innovación educativa en el currículum de la Educación Superior." },
      { id: "03", title: "Innovación curricular y comunitaria", desc: "TFG, TFM y Tesis que vinculan la formación con la comunidad, el contexto profesional y los ODS." },
    ],
  },
  formatos: {
    title: "Formatos de participación",
    items: [
      {
        f: "Comunicación",
        len: "Presencial (EHU o ULEAM) u online · 15 min",
        desc: "Presentación oral breve de trabajos teóricos, propuestas o resultados de investigación. Resumen de 200–300 palabras: tema, objetivos, metodología y resultados.",
      },
      {
        f: "Innovaciones o experiencias didácticas",
        len: "Online · 15 min",
        desc: "Presentaciones visuales breves que sintetizan de forma clara y estructurada un trabajo de investigación, de innovación o de experiencia relevante. Resumen usando la plantilla oficial.",
        url: "https://canva.link/g47tvl157m7px79",
        urlLabel: "Descargar plantilla Canva",
      },
      {
        f: "Simposio",
        len: "Presencial (EHU o ULEAM) · hasta 60 min",
        desc: "Sesión temática coordinada. Incluye introducción del coordinador/a, contribuciones complementarias y turno de preguntas. Propuesta: resumen del simposio (100 palabras) + resúmenes de cada intervención (150–200 palabras).",
      },
    ],
  },
  propuestas: {
    title: "Envío de propuestas",
    lead: "Plazo abierto hasta el 15 de septiembre incluido. Evaluación por pares.",
    timeline: [
      { date: "Hasta 15 Sep 2026", label: "Cierre de envío de propuestas", status: "open" },
      { date: "Hasta 30 Sep 2026", label: "Notificación: aceptación, revisión o rechazo", status: "soon" },
      { date: "Antes del 15 Oct 2026", label: "Matrícula de trabajos aceptados — solo autores con trabajo aprobado", status: "future", url: "https://forms.gle/jeQCEYQ3TjAFGwdR6" },
      { date: "Antes del 20 Oct 2026", label: "Envío de material de apoyo a la presentación", status: "future" },
      { date: "28–30 Octubre 2026", label: "Presentación en el congreso (formato híbrido)", status: "future" },
      { date: "Hasta 15 Nov 2026", label: "Envío del trabajo extenso (publicación opcional)", status: "future" },
    ],
    normas: {
      idiomas: "Euskara, español e inglés",
      extension: "Mín. 200 — máx. 300 palabras",
      estructura: "Introducción, objetivos, método, resultados y conclusiones",
      metodologia: "Cuando no sean trabajos estrictamente de investigación, especificar la metodología seguida.",
    },
    materiales: [
      { tipo: "Formulario de envío", desc: "Enviar propuesta de trabajo", url: "https://forms.gle/er4VkFhmJDhxDDuv6", urlLabel: "Abrir formulario" },
      { tipo: "Plantilla Canva (Innovaciones)", desc: "Para innovaciones y experiencias didácticas", url: "https://canva.link/g47tvl157m7px79", urlLabel: "Ver plantilla" },
      { tipo: "Matrícula de trabajos aceptados", desc: "Formalizar inscripción tras recibir notificación de aceptación", url: "https://forms.gle/jeQCEYQ3TjAFGwdR6", urlLabel: "Formulario matrícula" },
    ],
  },
  presentacionDia: {
    title: "Programa",
    lead: "Próximamente se publicará información detallada sobre el programa y las conferencias.",
    items: [],
    nota: "",
  },
  publicacion: {
    title: "Publicación de los trabajos (opcional)",
    lead: "Edición de un libro con la Editorial Octaedro. Todos los autores matriculados recibirán una copia en PDF.",
    octaedro: {
      h: "Editorial Octaedro",
      body: "Editorial de prestigio nacional. Posición 48 de 272 en la clasificación general del Scholarly Publishers Indicators. En el área de educación, posición 12 de 94.",
    },
    deadline: "15 de noviembre de 2026 — entrega del trabajo extenso",
    norms: {
      formato: "Microsoft Word · plantilla del congreso",
      extension: "10–20 páginas · 4 000–8 000 palabras",
      tipografia: "Calibri 10 pt · espaciado sencillo · justificado",
      referencias: "APA 6ª edición · sin notas a pie de página",
      figuras: "Figuras originales en JPG buena resolución, intercaladas. Tablas como texto, no como imagen.",
    },
    estructuras: [
      { tipo: "Investigación", body: "Introducción · método · resultados · conclusiones · referencias" },
      { tipo: "Experiencias", body: "Introducción · descripción · resultados · conclusiones · referencias" },
      { tipo: "Teórico / innovación", body: "Introducción · desarrollo · conclusiones · referencias" },
    ],
    elementos: [
      "Título en el idioma original y en inglés",
      "Nombre, institución y país de cada autor/a",
      "Correo electrónico de contacto",
      "Resumen 150–220 palabras + abstract en inglés",
      "3–5 palabras clave + keywords",
    ],
  },
  organizadoras: {
    title: "Entidades organizadoras",
    items: [
      { name: "Facultad de Educación de Bilbao", parent: "Universidad del País Vasco · EHU", country: "España" },
      { name: "Universidad Laica Eloy Alfaro", parent: "ULEAM · Manabí", country: "Ecuador" },
    ],
  },
  comites: {
    title: "Comités del congreso",
    lead: "La organización del congreso reúne a investigadores e investigadoras de la EHU, ULEAM y universidades colaboradoras de España, Ecuador, Colombia, Argentina, Estados Unidos, Holanda y Hungría.",
    grupos: [
      {
        nombre: "Comité organizador",
        kicker: "Coordinación general del congreso",
        miembros: [
          { n: "Isra Alonso", a: "EHU" },
          { n: "Asier Romero", a: "EHU" },
          { n: "Nahia Idoiaga", a: "EHU" },
          { n: "Amaia Eiguren", a: "EHU" },
          { n: "Mari Mar Boillos", a: "EHU" },
          { n: "Jhonny Villafuerte", a: "EHU / ULEAM" },
          { n: "Pedro Quijije Anchiundia", a: "PhD · Decano ULEAM" },
          { n: "German Carrera", a: "PhD · ULEAM" },
          { n: "Lewin Pérez", a: "PhD · ULEAM" },
          { n: "Johanna Bello", a: "Mg. · ULEAM" },
          { n: "Diana Zambrano", a: "Mg. · ULEAM" },
        ],
      },
      {
        nombre: "Comité científico",
        kicker: "Evaluación por pares de las propuestas",
        miembros: [
          { n: "Iñigo Rodríguez", a: "EHU" },
          { n: "Leire Darretxe", a: "EHU" },
          { n: "Itziar Kerexeta", a: "EHU" },
          { n: "Saioa Bilbao", a: "EHU" },
          { n: "Estibaliz Amenarro", a: "EHU" },
          { n: "Naiara Berasategi", a: "EHU" },
          { n: "Idoia Legorburu", a: "EHU" },
          { n: "Maitane Picaza", a: "EHU" },
          { n: "Nagore Ozerinjauregi", a: "EHU" },
          { n: "Nekane Beloki", a: "EHU" },
          { n: "Cristina Arriaga", a: "EHU" },
          { n: "Isra Alonso", a: "EHU" },
          { n: "Asier Romero", a: "EHU" },
          { n: "Nahia Idoiaga", a: "EHU" },
          { n: "Amaia Eiguren", a: "EHU" },
          { n: "José Antonio Marín", a: "Universidad de Granada" },
          { n: "Francisco José Castillo Hernández", a: "Universidad de Groningen (Holanda)" },
          { n: "Eva Markus", a: "Eötvös Loránd University (Hungría)" },
          { n: "Arturo Rodríguez", a: "PhD · ULEAM" },
          { n: "Lady Vanessa Mendoza", a: "PhD · ULEAM" },
          { n: "Jessenia Sacoto", a: "PhD · ULEAM" },
          { n: "Miguel Cartaya", a: "PhD · ULEAM" },
          { n: "Jhonny Villafuerte", a: "PhD · ULEAM" },
          { n: "Eder Intriago", a: "PhD · Kansas State University (USA)" },
          { n: "Antonieta Morales", a: "PhD · Univ. de Guayaquil" },
          { n: "María Asunción Rojas", a: "PhD · Univ. de Guayaquil" },
          { n: "Pablo Teneglia", a: "PhD · Univ. de Córdoba (Argentina)" },
          { n: "Diana Concha", a: "Mg. · Red COMEDI" },
          { n: "Diana Katherine González", a: "PhD · UCEVA, Colombia" },
          { n: "Andrea Soto", a: "PhD · UCEVA, Colombia" },
          { n: "Anna Maria Escofet Roig", a: "Universidad de Barcelona" },
          { n: "Brenda Nazarena Bär Kwast", a: "Universidad de Barcelona" },
          { n: "María del Mar Román García", a: "UNED" },
          { n: "Fátima Avilés", a: "Universidad de Barcelona" },
          { n: "Elena López de Arana Prado", a: "Univ. Autónoma de Madrid" },
          { n: "Sebastià Verger", a: "Univ. de las Islas Baleares" },
          { n: "Ana Josefa Cañas", a: "Univ. de las Islas Baleares" },
          { n: "Oihane Korres Alonso", a: "Universidad de Deusto" },
          { n: "Oscar Martínez Rivera", a: "Universitat Ramon Llull" },
          { n: "Noelia Ceballos López", a: "Universidad de Cantabria" },
          { n: "Angela Saiz Linares", a: "Universidad de Cantabria" },
        ],
      },
      {
        nombre: "Comité editorial",
        kicker: "Coordinación de la publicación con Octaedro",
        miembros: [
          { n: "Monike Gezuraga", a: "EHU" },
          { n: "Estibaliz Amenarro", a: "EHU" },
          { n: "Naiara Berasategi", a: "EHU" },
          { n: "Idoia Legorburu", a: "EHU" },
          { n: "Maitane Picaza", a: "EHU" },
          { n: "Nagore Ozerinjauregi", a: "EHU" },
          { n: "Ane Gabikagogeaskoa", a: "EHU" },
          { n: "Isra Alonso", a: "EHU" },
          { n: "Asier Romero", a: "EHU" },
          { n: "Nahia Idoiaga", a: "EHU" },
          { n: "Amaia Eiguren", a: "EHU" },
          { n: "Isidro Alcívar", a: "Mg. · ULEAM" },
          { n: "Alberto Quijije", a: "Mg. · ULEAM" },
          { n: "Jorge Corral", a: "Mg. · ULEAM" },
          { n: "Anabel Alcívar", a: "PhD · ULEAM" },
          { n: "Anita Rivera", a: "Mg. · ULEAM" },
          { n: "Monica Eliece", a: "PhD · Universidad de Deusto" },
        ],
      },
    ],
  },
  footer: {
    contact: "arturo.rodriguez@uleam.edu.ec",
    contact2: "ane.gabikagogeaskoa@ehu.eus",
    copy: "© 2026 CIIIES · Organizado por la ULEAM y la Facultad de Educación de Bilbao (EHU)",
  },
};

window.CONTENT_EHU = CONTENT_EHU;
