// Contenido INEDUS 2026 — trilingüe: es / eu / en
// Las listas de miembros son compartidas (no se traducen).

const _ORG = [
  { n: "Amaia Eiguren", a: "EHU" },
  { n: "Pedro Quijije Anchiundia", a: "ULEAM" },
  { n: "Asier Romero", a: "EHU" },
  { n: "Diana Zambrano", a: "ULEAM" },
  { n: "German Carrera", a: "ULEAM" },
  { n: "Isra Alonso", a: "EHU" },
  { n: "Jhonny Villafuerte", a: "EHU / ULEAM" },
  { n: "Johanna Bello", a: "ULEAM" },
  { n: "Lewin Pérez", a: "ULEAM" },
  { n: "Mari Mar Boillos", a: "EHU" },
  { n: "Nahia Idoiaga", a: "EHU" },
];

const _SCI = [
  { n: "Amaia Eiguren", a: "EHU" },
  { n: "Ana Josefa Cañas", a: "Universidad de las Islas Baleares" },
  { n: "Andrea Soto", a: "UCEVA" },
  { n: "Angela Saiz Linares", a: "Universidad de Cantabria" },
  { n: "Anna Maria Escofet Roig", a: "Universidad de Barcelona" },
  { n: "Antonieta Morales", a: "Universidad de Guayaquil" },
  { n: "Arturo Rodríguez", a: "ULEAM" },
  { n: "Asier Romero", a: "EHU" },
  { n: "Brenda Nazarena Bär Kwast", a: "Universidad de Barcelona" },
  { n: "Cristina Arriaga", a: "EHU" },
  { n: "Diana Concha", a: "Red COMEDI" },
  { n: "Diana Katherine González", a: "UCEVA" },
  { n: "Eder Intriago", a: "Kansas State University" },
  { n: "Elena López de Arana Prado", a: "Universidad Autónoma de Madrid" },
  { n: "Estibaliz Amenarro", a: "EHU" },
  { n: "Eva Markus", a: "Eötvös Loránd University" },
  { n: "Fátima Avilés", a: "Universidad de Barcelona" },
  { n: "Francisco José Castillo Hernández", a: "Universidad de Groningen" },
  { n: "Idoia Legorburu", a: "EHU" },
  { n: "Iñigo Rodríguez", a: "EHU" },
  { n: "Isra Alonso", a: "EHU" },
  { n: "Itziar Kerexeta", a: "EHU" },
  { n: "Jessenia Sacoto", a: "ULEAM" },
  { n: "Jhonny Villafuerte", a: "ULEAM" },
  { n: "José Antonio Marín", a: "Universidad de Granada" },
  { n: "Lady Vanessa Mendoza", a: "ULEAM" },
  { n: "Leire Darretxe", a: "EHU" },
  { n: "Maitane Picaza", a: "EHU" },
  { n: "María Asunción Rojas", a: "Instituto Tecnológico Superior Blue Hill College" },
  { n: "María del Mar Román García", a: "UNED" },
  { n: "Miguel Cartaya", a: "ULEAM" },
  { n: "Nagore Ozerinjauregi", a: "EHU" },
  { n: "Nahia Idoiaga", a: "EHU" },
  { n: "Naiara Berasategi", a: "EHU" },
  { n: "Nekane Beloki", a: "EHU" },
  { n: "Noelia Ceballos López", a: "Universidad de Cantabria" },
  { n: "Oihane Korres Alonso", a: "Universidad de Deusto" },
  { n: "Oscar Martínez Rivera", a: "Universitat Ramon Llull" },
  { n: "Pablo Teneglia", a: "Universidad de Córdoba" },
  { n: "Saioa Bilbao", a: "EHU" },
  { n: "Sebastià Verger", a: "Universidad de las Islas Baleares" },
];

const _ED = [
  { n: "Alberto Quijije", a: "ULEAM" },
  { n: "Amaia Eiguren", a: "EHU" },
  { n: "Anabel Alcívar", a: "ULEAM" },
  { n: "Ane Gabikagogeaskoa", a: "EHU" },
  { n: "Anita Rivera", a: "ULEAM" },
  { n: "Asier Romero", a: "EHU" },
  { n: "Estibaliz Amenarro", a: "EHU" },
  { n: "Idoia Legorburu", a: "EHU" },
  { n: "Isidro Alcívar", a: "ULEAM" },
  { n: "Isra Alonso", a: "EHU" },
  { n: "Jorge Corral", a: "ULEAM" },
  { n: "Maitane Picaza", a: "EHU" },
  { n: "Mónica Elices", a: "Universidad de Deusto" },
  { n: "Monike Gezuraga", a: "EHU" },
  { n: "Nagore Ozerinjauregi", a: "EHU" },
  { n: "Nahia Idoiaga", a: "EHU" },
  { n: "Naiara Berasategi", a: "EHU" },
];

const _ORGS = [
  { name: "Facultad de Educación de Bilbao", parent: "Universidad del País Vasco · EHU", country: "España" },
  { name: "Universidad Laica Eloy Alfaro", parent: "ULEAM · Facultad de Educación y Turismo · Manta", country: "Ecuador" },
];

const CONTENT_EHU = {
  es: {
    eventShort: "INEDUS 2026",
    eventFull: "Congreso Internacional de Innovación Educativa y Sostenibilidad en Educación Superior",
    subtitle: "Intercambio de experiencias",
    tagline: "Un diálogo entre los formadores de docentes de Iberoamérica",
    heroTitleParts: ["Innovación Educativa", "y Sostenibilidad", "en Educación Superior"],
    dates: "28, 29 y 30 de Octubre 2026",
    location: "Facultad de Educación de Bilbao (EHU) · ULEAM (Ecuador)",
    hybrid: "Formato online y presencial · doble sede",
    venues: {
      v1label: "Sede 1 · Europa",
      v1name: "Facultad de Educación de Bilbao",
      v1detail: "Universidad del País Vasco · EHU",
      v2label: "Sede 2 · América Latina",
      v2name: "ULEAM",
      v2detail: "Facultad de Educación y Turismo · Manta, Ecuador",
    },
    nav: {
      presentacion: "Presentación",
      destinatarios: "Destinatarios",
      propuestas: "Propuestas",
      matricula: "Matrícula",
      programa: "Programa",
      contacto: "Contacto",
    },
    heroLead: "Tres días de comunicaciones, pósters y simposios sobre innovación educativa y sostenibilidad en el marco de los Objetivos de Desarrollo Sostenible en la Educación Superior, con doble sede en Bilbao y Manta.",
    ctas: {
      submit: "Enviar propuesta",
      program: "Ver programa",
      download: "Descargar plantilla",
    },
    stats: [
      { n: "3", l: "Días de congreso" },
      { n: "2", l: "Sedes presenciales" },
      { n: "7+", l: "Países participantes" },
      { n: "3", l: "Idiomas aceptados" },
    ],
    ui: {
      cfpAside: "Según tu formato",
      cfpForms: "Formularios",
      contactKicker: "Contacto",
      contactH: "¿Dudas sobre el envío o la matrícula?",
      pubDeadline: "Fecha límite",
      pubSpecs: "Especificaciones",
      pubFormat: "Formato",
      pubExt: "Extensión",
      pubTypo: "Tipografía",
      pubRefs: "Referencias",
      pubFigs: "Figuras",
      pubStructureHead: "Estructura del trabajo en extenso",
      pubElemsHead: "Elementos obligatorios del texto",
      membros: "miembros",
      verBases: "Ver bases de envío →",
    },
    presentacion: {
      title: "Sobre el congreso",
      lead: 'El congreso internacional "Innovación educativa, Inclusión y Sostenibilidad" crea un entorno en el que educadores y estudiantes de Iberoamérica y el mundo pueden compartir vivencias y aprender unos de otros.',
      objetivos: [
        { id: "01", title: "Intercambio cultural internacional", desc: "Facilitar la comprensión de los distintos enfoques educativos y de sostenibilidad en ambos países." },
        { id: "02", title: "Fortalecer habilidades nuevas", desc: "Proporcionar estrategias y metodologías que integren la sostenibilidad en los procesos de enseñanza." },
        { id: "03", title: "Iniciativas colaborativas", desc: "Motivar a los participantes a trabajar juntos en proyectos que aborden retos medioambientales locales y globales." },
        { id: "04", title: "Conciencia ambiental", desc: "Destacar la relevancia de formar en temas ecológicos y su impacto en la comunidad." },
        { id: "05", title: "Red de colaboración", desc: "Conectar a educadores y estudiantes con un compromiso compartido con la sostenibilidad y el aprendizaje continuo." },
      ],
    },
    destinatarios: {
      title: "Público (Dirigido a)",
      lead: "Profesorado y alumnado universitario interesado en la innovación educativa.",
      items: [
        "Docentes e investigadores/as de universidades de España, Ecuador y universidades internacionales colaboradoras",
        "Alumnado de grado y posgrado en proyectos de innovación docente",
        "Profesionales del ámbito escolar y de la Educación Social",
        "Responsables de practicum, comunicaciones de Trabajos de Fin de Grado (TFG), Trabajos de Fin de Máster (TFM) y Tesis Doctorales",
      ],
    },
    lineas: {
      title: "Líneas temáticas",
      lead: "Tres líneas para presentar trabajos en formato científico.",
      items: [
        { id: "01", title: "Trabajos teóricos o empíricos", desc: "Sobre temáticas relacionadas con educación y sostenibilidad en la Educación Superior." },
        { id: "02", title: "Experiencias prácticas de innovación", desc: "Innovación educativa en el currículum de la Educación Superior." },
        { id: "03", title: "Innovación curricular y comunitaria", desc: "TFG, TFM y Tesis que vinculan la formación con la comunidad, el contexto profesional y los ODS." },
      ],
    },
    formatos: {
      title: "Formatos de participación",
      items: [
        {
          f: "Comunicación",
          len: "Presencial (EHU o ULEAM) u online · 15 min",
          desc: "Presentación oral breve de trabajos teóricos, propuestas o resultados de investigación. Resumen de 200–300 palabras: tema, objetivos, metodología y resultados.",
        },
        {
          f: "Innovaciones o experiencias didácticas",
          len: "Presencial (EHU o ULEAM) · 15 min",
          desc: "Presentaciones visuales breves que sintetizan de forma clara y estructurada un trabajo de investigación, de innovación o de experiencia relevante. Resumen usando la plantilla oficial.",
          url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx",
          urlLabel: "Descargar plantilla",
        },
        {
          f: "Simposio",
          len: "Presencial (EHU o ULEAM) u online · hasta 60 min",
          desc: "Sesión temática coordinada. Incluye introducción del coordinador/a, contribuciones complementarias y turno de preguntas. Propuesta: resumen del simposio (100 palabras) + resúmenes de cada intervención (150–200 palabras).",
        },
      ],
    },
    propuestas: {
      title: "Envío de propuestas",
      lead: "Plazo abierto hasta el 15 de septiembre de 2026. Se aceptan propuestas en español, euskara e inglés. Evaluación por pares.",
      timeline: [
        { date: "Hasta 15 Sep 2026", label: "Cierre de envío de propuestas", status: "open" },
        { date: "Hasta 30 Sep 2026", label: "Notificación: aceptación, revisión o rechazo", status: "soon" },
        { date: "Antes del 15 Oct 2026", label: "Matrícula de trabajos aceptados — solo autores con trabajo aprobado", status: "future" },
        { date: "Antes del 20 Oct 2026", label: "Envío de material de apoyo a la presentación", status: "future" },
        { date: "28–30 Octubre 2026", label: "Presentación en el congreso (formato híbrido)", status: "future" },
        { date: "Hasta 15 Nov 2026", label: "Envío del trabajo extenso (publicación opcional)", status: "future" },
      ],
      normas: {
        idiomas: "Español · Euskara · English",
        evaluacion: "Evaluación por pares · Notificación antes del 30 Sep",
        checklist: [
          "Nombre, institución y email (propios y de coautores)",
          "Título de la propuesta",
          "Línea temática y formato elegidos",
          "Idioma de presentación",
        ],
        porFormato: [
          { f: "Comunicación", req: "Resumen 200–300 palabras: tema, objetivos, metodología, resultados" },
          { f: "Innovaciones", req: "PDF desde plantilla oficial", url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx" },
          { f: "Simposio", req: "Resumen general 100 pal. + resúmenes por ponente 150–200 pal." },
        ],
      },
      materiales: [],
    },
    matricula: {
      title: "Matrícula y publicación",
      lead: "El pago de la matrícula no se realizará hasta la aceptación del trabajo. Todos los firmantes del trabajo (autores) deberán inscribirse y abonar la cuota de matrícula. Plazo: antes del 15 de octubre. Envío del trabajo completo (opcional) hasta el 15 de noviembre.",
      tarifasTitle: "Cuotas de matriculación",
      tarifasNota: "La aceptación de las propuestas se hará efectiva mediante la inscripción antes del 15 de octubre. Todos los autores deberán formalizar su matrícula.",
      tarifas: [
        { label: "Profesionales del ámbito de la educación formal y la educación social, y personas desempleadas", price: "GRATIS", note: "Plazas limitadas" },
        { label: "Profesorado e investigadores/as de EHU y ULEAM", price: "25 €" },
        { label: "Profesorado e investigadores/as universitarios/as", price: "50 €" },
        { label: "Profesorado e investigadores/as de universidades de América del Norte y Central, África y Asia", price: "25 €" },
      ],
      instruccion: "El pago debe realizarse mediante transferencia bancaria a la siguiente cuenta:",
      iban: "ES34 2095 0292 9010 6117 3778",
      swift: "BASKES2BXXX",
      concepto: "Congreso_Apellido1NOMBRE",
      conceptoLabel: "Concepto / Asunto",
      nota: "Sustituye «Apellido1NOMBRE» por tu primer apellido y nombre, sin espacios. Ejemplo: Congreso_RodriguezArturo",
    },
    presentacionDia: {
      title: "Programa",
      lead: "Próximamente se publicará información detallada sobre el programa y las conferencias.",
      items: [],
      nota: "",
    },
    publicacion: {
      title: "Publicación de los trabajos (opcional)",
      lead: "Edición de un libro con la Editorial Octaedro. Todos los autores matriculados recibirán una copia en PDF.",
      octaedro: {
        h: "Editorial Octaedro",
        body: "Editorial de prestigio nacional. Posición 48 de 272 en la clasificación general del Scholarly Publishers Indicators. En el área de educación, posición 12 de 94.",
      },
      deadline: "15 de noviembre de 2026 — entrega del trabajo extenso",
      norms: {
        formato: "Microsoft Word · plantilla del congreso",
        extension: "10–20 páginas · 4 000–8 000 palabras",
        tipografia: "Calibri 10 pt · espaciado sencillo · justificado",
        referencias: "APA 6ª edición · sin notas a pie de página",
        figuras: "Figuras originales en JPG buena resolución, intercaladas. Tablas como texto, no como imagen.",
      },
      estructuras: [
        { tipo: "Investigación", body: "Introducción · método · resultados · conclusiones · referencias" },
        { tipo: "Experiencias", body: "Introducción · descripción · resultados · conclusiones · referencias" },
        { tipo: "Teórico / innovación", body: "Introducción · desarrollo · conclusiones · referencias" },
      ],
      elementos: [
        "Título en el idioma original y en inglés",
        "Nombre, institución y país de cada autor/a",
        "Correo electrónico de contacto",
        "Resumen 150–220 palabras + abstract en inglés",
        "3–5 palabras clave + keywords",
      ],
    },
    organizadoras: {
      title: "Entidades organizadoras",
      items: _ORGS,
    },
    comites: {
      title: "Comités del congreso",
      lead: "La organización del congreso reúne a investigadores e investigadoras de la EHU, ULEAM y universidades colaboradoras de España, Ecuador, Colombia, Argentina, Estados Unidos, Holanda y Hungría.",
      grupos: [
        { nombre: "Comité organizador", kicker: "Coordinación general del congreso", miembros: _ORG },
        { nombre: "Comité científico", kicker: "Evaluación por pares de las propuestas", miembros: _SCI },
        { nombre: "Comité editorial", kicker: "Coordinación de la publicación con Octaedro", miembros: _ED },
      ],
    },
    footer: {
      contact: "arturo.rodriguez@uleam.edu.ec",
      contact2: "ane.gabikagogeaskoa@ehu.eus",
      contactSection: "jhonny.villafuerte@uleam.edu.ec",
      contact2Section: "ane.gabikagogeaskoa@ehu.eus",
      copy: "© 2026 INEDUS · Organizado por la Facultad de Educación y Turismo (FET) de la ULEAM y la Facultad de Educación de Bilbao (EHU) de la Universidad del País Vasco",
    },
  },

  eu: {
    eventShort: "INEDUS 2026",
    eventFull: "Nazioarteko Kongresua Hezkuntza Berrikuntzan eta Jasangarritasunean Goi Mailako Hezkuntzan",
    subtitle: "Esperientzien Trukea",
    tagline: "Iberoamerikako irakasle-hezitzaileen arteko elkarrizketa",
    heroTitleParts: ["Hezkuntza Berrikuntza", "eta Jasangarritasuna", "Goi Mailako Hezkuntzan"],
    dates: "Urriak 28, 29 eta 30, 2026",
    location: "Bilboko Hezkuntza Fakultatea (EHU) · ULEAM (Ecuador)",
    hybrid: "Online eta presentzial formatua · bi egoitza",
    venues: {
      v1label: "1. egoitza · Europa",
      v1name: "Bilboko Hezkuntza Fakultatea",
      v1detail: "Euskal Herriko Unibertsitatea · EHU",
      v2label: "2. egoitza · Latinoamerika",
      v2name: "ULEAM",
      v2detail: "Hezkuntza eta Turismo Fakultatea · Manta, Ecuador",
    },
    nav: {
      presentacion: "Aurkezpena",
      destinatarios: "Hartzaileak",
      propuestas: "Proposamenak",
      matricula: "Matrikula",
      programa: "Programa",
      contacto: "Kontaktua",
    },
    heroLead: "Hiru eguneko komunikazioak, posterrak eta sinposioak hezkuntza-berrikuntzari eta jasangarritasunari buruz, Garapen Jasangarrirako Helburuen esparruan Goi Mailako Hezkuntzan, bi egoitza nagusirekin Bilbon eta Mantan.",
    ctas: {
      submit: "Proposamena bidali",
      program: "Programa ikusi",
      download: "Txantiloia deskargatu",
    },
    stats: [
      { n: "3", l: "Kongresu egun" },
      { n: "2", l: "Egoitza presentzial" },
      { n: "7+", l: "Herrialde parte-hartzaile" },
      { n: "3", l: "Onartutako hizkuntzak" },
    ],
    ui: {
      cfpAside: "Zure formatuaren arabera",
      cfpForms: "Inprimakiak",
      contactKicker: "Kontaktua",
      contactH: "Zalantzarik bidalketa edo matrikulazioarekin?",
      pubDeadline: "Muga-eguna",
      pubSpecs: "Zehaztapenak",
      pubFormat: "Formatua",
      pubExt: "Luzera",
      pubTypo: "Tipografia",
      pubRefs: "Erreferentziak",
      pubFigs: "Irudiak",
      pubStructureHead: "Lan osoaren egitura",
      pubElemsHead: "Testuko elementu nahitaezkoak",
      membros: "kide",
      verBases: "Oinarriak ikusi →",
    },
    presentacion: {
      title: "Kongresua",
      lead: "«Hezkuntza berrikuntza eta iraunkortasuna Goi Mailako Hezkuntzan» programaren helburua parte hartzaileek beren esperientziak partekatu eta elkarrengandik ikasi ahal izatea da, horretarako ingurune bat sortuz.",
      objetivos: [
        { id: "01", title: "Nazioarteko kultura-trukea", desc: "Bi herrialdeetan hartutako hezkuntza eta iraunkortasun ikuspegiak ulertzen laguntzea." },
        { id: "02", title: "Trebetasun berriak indartzea", desc: "Irakatsi eta ikasteko prozesuetan iraunkortasuna integratuko duten estrategiak eta metodologiak ematea." },
        { id: "03", title: "Elkarlaneko ekimenak", desc: "Parte-hartzaileak motibatzea ingurumen-erronkei heltzen dieten proiektuetan batera lan egitera, toki-mailan zein globalean." },
        { id: "04", title: "Ingurumen-kontzientzia", desc: "Gai ekologikoetan herritarrak trebatzearen garrantzia azpimarratzea eta horrek komunitatean duen eragina aztertzea." },
        { id: "05", title: "Lankidetza-sarea", desc: "Iraunkortasunarekin eta etengabeko ikaskuntzarekin konprometitutako irakasleak eta ikasleak konektatzea." },
      ],
    },
    destinatarios: {
      title: "Hartzaileak",
      lead: "Nazioarteko biltzar hau hezkuntza-berrikuntzari lotutako irakasle eta unibertsitateko ikasleei zuzenduta dago.",
      items: [
        "EHUko, ULEAMeko eta nazioarteko gonbidatutako unibertsitateetako irakasleak eta ikertzaileak",
        "Gradu eta masterreko ikasleak irakaskuntza-berrikuntzako proiektuetan",
        "Eskola eta gizarte-hezkuntzako profesionalak",
        "Practikuma, GrAL, MAL eta doktorego-tesiak garatzen laguntzeko arduradunak",
      ],
    },
    lineas: {
      title: "Ildo tematikoak",
      lead: "Hiru lerro lan zientifiko formatuan aurkezteko.",
      items: [
        { id: "01", title: "Lan teorikoak edo enpirikoak", desc: "Hezkuntzaren eta jasangarritasunaren arteko elkargunea jorratzen duten ikerketa teorikoak edo enpirikoak, goi-mailako hezkuntzaren eremuan." },
        { id: "02", title: "Hezkuntza-berrikuntzako esperientzia praktikoak", desc: "Jasangarritasuna, ikaskuntza aktiboa edo metodologia eraldatzaileak unibertsitate-curriculumean integratzen dituzten esperientziak." },
        { id: "03", title: "Curriculum-berrikuntza eta lan akademikoak", desc: "GrAL, MAL eta doktorego-tesiak unibertsitate-prestakuntzaren, lanbide-ingurunearen eta GJHen arteko lotura sustatzen dutenak." },
      ],
    },
    formatos: {
      title: "Parte-hartze formatuak",
      items: [
        {
          f: "Komunikazioa",
          len: "Aurrezkoa (EHU edo ULEAM) edo online · 15 min",
          desc: "15 minutuko ahozko aurkezpen laburrak, lan teorikoak, proposamenak edo ikerketa-emaitzak azaltzen dituztenak. 200–300 hitzeko laburpena: gaia, helburuak, metodologia eta emaitzak.",
        },
        {
          f: "Berrikuntza edo esperientzia didaktikoak",
          len: "Aurrezkoa (EHU edo ULEAM) · 15 min",
          desc: "15 minutuko aurkezpen bisual laburrak, ikerketa edo berrikuntza-lan bat modu argi eta egituratuan laburbiltzen dutenak. Laburpena txantiloi ofizialaren bidez.",
          url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx",
          urlLabel: "Txantiloia deskargatu",
        },
        {
          f: "Sinposioa",
          len: "Aurrezkoa (EHU edo ULEAM) edo online · 60 min arte",
          desc: "Aldez aurretik koordinatzaileak antolatutako saio tematikoa. Koordinatzailearen sarrera, elkarren osagarri diren ekarpenak eta galdera-txanda. Proposamena: sinposioaren laburpena (100 hitz) + hitzaldi bakoitzarena (150–200 hitz).",
        },
      ],
    },
    propuestas: {
      title: "Proposamenak bidaltzea",
      lead: "Lanak aurkezteko epea irailaren 15era arte egongo da zabalik. Proposamenak euskaraz, gaztelaniaz eta ingelesez onartzen dira. Pareka ebaluatuko dira.",
      timeline: [
        { date: "Irailaren 15a arte", label: "Proposamenak bidaltzeko epea", status: "open" },
        { date: "Irailaren 30a arte", label: "Jakinarazpena: onarpena, berrikuspena edo errefusapena", status: "soon" },
        { date: "Urriaren 15a baino lehen", label: "Matrikula — onartutako lanen egileak soilik", status: "future" },
        { date: "Urriaren 20a baino lehen", label: "Aurkezpenerako material lagungarria bidaltzea", status: "future" },
        { date: "Urriak 28–30", label: "Kongresuan aurkeztea (formatu hibridoan)", status: "future" },
        { date: "Azaroaren 15a arte", label: "Lan osoaren bidalketa (argitalpena, aukerakoa)", status: "future" },
      ],
      normas: {
        idiomas: "Euskara · Gaztelania · English",
        evaluacion: "Pareka ebaluatuko da · Jakinarazpena irailaren 30a baino lehen",
        checklist: [
          "Izena, erakundea eta posta elektronikoa (egileenak eta koegileena)",
          "Proposamenaren izenburua",
          "Ildo tematikoa eta aukeratutako formatua",
          "Aurkezpenaren hizkuntza",
        ],
        porFormato: [
          { f: "Komunikazioa", req: "Laburpena 200–300 hitz: gaia, helburuak, metodologia, emaitzak" },
          { f: "Berrikuntzak", req: "PDF txantiloi ofizialetik", url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx" },
          { f: "Sinposioa", req: "Laburpen orokorra 100 hitz + ponente bakoitzeko laburpena 150–200 hitz" },
        ],
      },
      materiales: [],
    },
    matricula: {
      title: "Matrikula eta argitalpena",
      lead: "Matrikularen ordainketa ez da egingo lana onartu arte. Lanaren sinatzaile guztiek (egileek) matrikula egin eta kuota ordaindu beharko dute. Epea: urriaren 15a baino lehen. Lan osoa (aukerakoa) azaroaren 15a arte.",
      tarifasTitle: "Matrikula-kuotak",
      tarifasNota: "Proposamenen onarpena urriaren 15a baino lehen egindako izena ematean bihurtuko da eraginkor. Egile guztiek matrikula formalizatu beharko dute.",
      tarifas: [
        { label: "Hezkuntza formaleko eta gizarte-hezkuntzako profesionalak, eta langabeak", price: "DOAN", note: "Plaza mugatuak" },
        { label: "EHUko eta ULEAMeko irakasle eta ikertzaileak", price: "25 €" },
        { label: "Unibertsitateko irakasle eta ikertzaileak", price: "50 €" },
        { label: "Ipar eta Erdialdeko Amerika, Afrika eta Asiako unibertsitateetako irakasle eta ikertzaileak", price: "25 €" },
      ],
      instruccion: "Ordainketa bankuko transferentziaren bidez egin behar da kontu honetara:",
      iban: "ES34 2095 0292 9010 6117 3778",
      swift: "BASKES2BXXX",
      concepto: "Congreso_Abizen1IZENA",
      conceptoLabel: "Kontzeptua / Gaia",
      nota: "«Abizen1IZENA» zure lehen abizena eta izena jarri, hutsune gabe. Adibidez: Congreso_RodriguezArturo",
    },
    presentacionDia: {
      title: "Programa",
      lead: "Laster argitaratuko dira programa eta hitzaldiei buruzko informazio zehatzak.",
      items: [],
      nota: "",
    },
    publicacion: {
      title: "Lanen argitalpena (aukerakoa)",
      lead: "Octaedro argitaletxearekin liburu bat argitaratzea. Matrikulatutako egile guztiek liburuaren kopia bat jasoko dute PDF formatuan.",
      octaedro: {
        h: "Octaedro argitaletxea",
        body: "Izen nazionaleko argitaletxea. Scholarly Publishers Indicators-en sailkapen orokorrean 272tik 48. postuan dago. Hezkuntzaren arloan, 94tik 12. postuan.",
      },
      deadline: "2026ko azaroaren 15a — lan osoaren entrega",
      norms: {
        formato: "Microsoft Word · kongresuaren txantiloia",
        extension: "10–20 orrialde · 4 000–8 000 hitz",
        tipografia: "Calibri 10 pt · lerroartea bakuna · justifikatua",
        referencias: "APA 6. edizioa · ez orri-oineko oharrik",
        figuras: "Jatorrizko irudiak JPG formatuan, behar bezala tartekatuta. Taulak testuan, ez pantaila-argazki gisa.",
      },
      estructuras: [
        { tipo: "Ikerketa", body: "Sarrera · metodoa · emaitzak · ondorioak · erreferentziak" },
        { tipo: "Esperientziak", body: "Sarrera · deskribapena · emaitzak · ondorioak · erreferentziak" },
        { tipo: "Teorikoa / berrikuntza", body: "Sarrera · garapena · ondorioak · erreferentziak" },
      ],
      elementos: [
        "Izenburua jatorrizko hizkuntzan eta ingelesez",
        "Egilearen izena, erakundea eta herrialdea",
        "Harremanetarako posta elektronikoa",
        "Laburpena 150–220 hitz + abstract ingelesez",
        "3–5 gako-hitz + keywords",
      ],
    },
    organizadoras: {
      title: "Antolatzaile erakundeak",
      items: _ORGS,
    },
    comites: {
      title: "Kongresuko batzordeak",
      lead: "Kongresua EHUko, ULEAMeko eta Espainia, Ecuador, Kolonbia, Argentina, Estatu Batuak, Herbehereak eta Hungariako unibertsitateetako ikertzaileen arteko elkarlanean antolatzen da.",
      grupos: [
        { nombre: "Batzorde antolatzailea", kicker: "Kongresua koordinatzea orokorrean", miembros: _ORG },
        { nombre: "Batzorde zientifikoa", kicker: "Proposamenen pareka ebaluatzea", miembros: _SCI },
        { nombre: "Argitalpen-batzordea", kicker: "Argitalpena Octaedro-rekin koordinatzea", miembros: _ED },
      ],
    },
    footer: {
      contact: "arturo.rodriguez@uleam.edu.ec",
      contact2: "ane.gabikagogeaskoa@ehu.eus",
      contactSection: "jhonny.villafuerte@uleam.edu.ec",
      contact2Section: "ane.gabikagogeaskoa@ehu.eus",
      copy: "© 2026 INEDUS · Bilboko Hezkuntza Fakultatea (EHU) eta ULEAM-ek antolatua",
    },
  },

  en: {
    eventShort: "INEDUS 2026",
    eventFull: "International Congress on Educational Innovation and Sustainability in Higher Education",
    subtitle: "Exchange of Experiences",
    tagline: "A dialogue among teacher educators from Latin America",
    heroTitleParts: ["Educational Innovation", "and Sustainability", "in Higher Education"],
    dates: "October 28–30, 2026",
    location: "Faculty of Education of Bilbao (EHU) · ULEAM (Ecuador)",
    hybrid: "Hybrid format · dual venue",
    venues: {
      v1label: "Venue 1 · Europe",
      v1name: "Faculty of Education of Bilbao",
      v1detail: "University of the Basque Country · UPV/EHU",
      v2label: "Venue 2 · Latin America",
      v2name: "ULEAM",
      v2detail: "Faculty of Education and Tourism · Manta, Ecuador",
    },
    nav: {
      presentacion: "About",
      destinatarios: "Audience",
      propuestas: "Proposals",
      matricula: "Registration",
      programa: "Programme",
      contacto: "Contact",
    },
    heroLead: "Three days of papers, posters and symposia on educational innovation and sustainability within the framework of the Sustainable Development Goals in Higher Education, with dual venues in Bilbao and Manta.",
    ctas: {
      submit: "Submit proposal",
      program: "View programme",
      download: "Download template",
    },
    stats: [
      { n: "3", l: "Congress days" },
      { n: "2", l: "In-person venues" },
      { n: "7+", l: "Participating countries" },
      { n: "3", l: "Accepted languages" },
    ],
    ui: {
      cfpAside: "By format",
      cfpForms: "Forms",
      contactKicker: "Contact",
      contactH: "Questions about submission or registration?",
      pubDeadline: "Deadline",
      pubSpecs: "Specifications",
      pubFormat: "Format",
      pubExt: "Length",
      pubTypo: "Typography",
      pubRefs: "References",
      pubFigs: "Figures",
      pubStructureHead: "Full paper structure",
      pubElemsHead: "Required text elements",
      membros: "members",
      verBases: "View submission guidelines →",
    },
    presentacion: {
      title: "About the Congress",
      lead: 'The international congress "Educational Innovation, Inclusion and Sustainability" creates a space where educators and students from Latin America and around the world can share experiences and learn from one another.',
      objetivos: [
        { id: "01", title: "International cultural exchange", desc: "Facilitate understanding of different educational and sustainability approaches in both countries." },
        { id: "02", title: "Strengthening new skills", desc: "Provide strategies and methodologies that integrate sustainability into teaching and learning processes." },
        { id: "03", title: "Collaborative initiatives", desc: "Motivate participants to work together on projects addressing environmental challenges, locally and globally." },
        { id: "04", title: "Environmental awareness", desc: "Highlight the importance of training in ecological topics and their impact on the community." },
        { id: "05", title: "Collaborative network", desc: "Connect educators and students with a shared commitment to sustainability and lifelong learning." },
      ],
    },
    destinatarios: {
      title: "Audience",
      lead: "Faculty and university students interested in educational innovation.",
      items: [
        "Faculty and researchers from universities in Spain, Ecuador and international partner universities",
        "Undergraduate and postgraduate students involved in teaching innovation projects",
        "Professionals from school and social education contexts",
        "Supervisors of practica, bachelor's theses (TFG), master's theses (TFM) and doctoral dissertations",
      ],
    },
    lineas: {
      title: "Thematic lines",
      lead: "Three lines for presenting work in scientific format.",
      items: [
        { id: "01", title: "Theoretical or empirical papers", desc: "On themes related to education and sustainability in Higher Education." },
        { id: "02", title: "Practical innovation experiences", desc: "Educational innovation in Higher Education curriculum." },
        { id: "03", title: "Curricular and community innovation", desc: "Bachelor's, master's and doctoral work linking training with the community, professional context and the SDGs." },
      ],
    },
    formatos: {
      title: "Participation formats",
      items: [
        {
          f: "Paper",
          len: "In-person (EHU or ULEAM) or online · 15 min",
          desc: "Short oral presentation of theoretical work, proposals or research results. Abstract of 200–300 words: topic, objectives, methodology and results.",
        },
        {
          f: "Innovation or didactic experience",
          len: "In-person (EHU or ULEAM) · 15 min",
          desc: "Short visual presentations summarising research, innovation or relevant experience clearly and structuredly. Abstract using the official template.",
          url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx",
          urlLabel: "Download template",
        },
        {
          f: "Symposium",
          len: "In-person (EHU or ULEAM) or online · up to 60 min",
          desc: "Thematically coordinated session. Includes coordinator introduction, complementary contributions and Q&A. Proposal: symposium abstract (100 words) + individual abstracts (150–200 words).",
        },
      ],
    },
    propuestas: {
      title: "Submitting Proposals",
      lead: "Open until 15 September 2026. Proposals accepted in Spanish, Basque (Euskara) and English. Peer review.",
      timeline: [
        { date: "Until 15 Sep 2026", label: "Proposal submission deadline", status: "open" },
        { date: "Until 30 Sep 2026", label: "Notification: acceptance, revision or rejection", status: "soon" },
        { date: "Before 15 Oct 2026", label: "Registration for accepted authors only", status: "future" },
        { date: "Before 20 Oct 2026", label: "Submission of presentation support materials", status: "future" },
        { date: "28–30 October 2026", label: "Congress presentations (hybrid format)", status: "future" },
        { date: "Until 15 Nov 2026", label: "Full paper submission (optional publication)", status: "future" },
      ],
      normas: {
        idiomas: "Spanish · Basque (Euskara) · English",
        evaluacion: "Peer review · Notification before 30 Sep",
        checklist: [
          "Name, institution and email (authors and co-authors)",
          "Proposal title",
          "Thematic line and chosen format",
          "Language of presentation",
        ],
        porFormato: [
          { f: "Paper", req: "Abstract 200–300 words: topic, objectives, methodology, results" },
          { f: "Innovation", req: "PDF from official template", url: "Plantilla%20Innovaciones%20y%20experiencias%20did%C3%A1cticas%20(1).docx" },
          { f: "Symposium", req: "General abstract 100 words + per-speaker abstracts 150–200 words" },
        ],
      },
      materiales: [],
    },
    matricula: {
      title: "Registration & Publication",
      lead: "Registration payment will not be processed until the work is accepted. All co-authors must register and pay the registration fee. Deadline: before 15 October. Full paper submission (optional) before 15 November.",
      tarifasTitle: "Registration fees",
      tarifasNota: "Acceptance of proposals becomes effective upon registration before 15 October. All authors must complete their registration.",
      tarifas: [
        { label: "Professionals in formal education and social education, and unemployed persons", price: "FREE", note: "Limited places" },
        { label: "Faculty and researchers at EHU and ULEAM", price: "€25" },
        { label: "Faculty and researchers at universities (general)", price: "€50" },
        { label: "Faculty and researchers from universities in North and Central America, Africa and Asia", price: "€25" },
      ],
      instruccion: "Payment must be made by bank transfer to the following account:",
      iban: "ES34 2095 0292 9010 6117 3778",
      swift: "BASKES2BXXX",
      concepto: "Congreso_Surname1NAME",
      conceptoLabel: "Reference / Subject",
      nota: "Replace «Surname1NAME» with your first surname and first name, no spaces. Example: Congreso_RodriguezArturo",
    },
    presentacionDia: {
      title: "Programme",
      lead: "Detailed information on the programme and keynote speakers will be published soon.",
      items: [],
      nota: "",
    },
    publicacion: {
      title: "Publication (optional)",
      lead: "Book published with Editorial Octaedro. All registered authors receive a PDF copy.",
      octaedro: {
        h: "Editorial Octaedro",
        body: "National publisher of prestige. Ranked 48 out of 272 in the Scholarly Publishers Indicators general ranking. Position 12 out of 94 in education.",
      },
      deadline: "15 November 2026 — full paper submission",
      norms: {
        formato: "Microsoft Word · congress template",
        extension: "10–20 pages · 4,000–8,000 words",
        tipografia: "Calibri 10 pt · single spacing · justified",
        referencias: "APA 6th edition · no footnotes",
        figuras: "Original figures in JPG, embedded. Tables as text, not screenshots.",
      },
      estructuras: [
        { tipo: "Research", body: "Introduction · method · results · conclusions · references" },
        { tipo: "Experiences", body: "Introduction · description · results · conclusions · references" },
        { tipo: "Theoretical / innovation", body: "Introduction · development · conclusions · references" },
      ],
      elementos: [
        "Title in the original language and in English",
        "Author(s) name, institution and country",
        "Contact email address",
        "Abstract 150–220 words + English abstract",
        "3–5 keywords",
      ],
    },
    organizadoras: {
      title: "Organising Institutions",
      items: _ORGS,
    },
    comites: {
      title: "Congress Committees",
      lead: "The congress is organised by researchers from EHU, ULEAM and partner universities in Spain, Ecuador, Colombia, Argentina, the United States, the Netherlands and Hungary.",
      grupos: [
        { nombre: "Organising Committee", kicker: "General congress coordination", miembros: _ORG },
        { nombre: "Scientific Committee", kicker: "Peer review of proposals", miembros: _SCI },
        { nombre: "Editorial Committee", kicker: "Publication coordination with Octaedro", miembros: _ED },
      ],
    },
    footer: {
      contact: "arturo.rodriguez@uleam.edu.ec",
      contact2: "ane.gabikagogeaskoa@ehu.eus",
      contactSection: "jhonny.villafuerte@uleam.edu.ec",
      contact2Section: "ane.gabikagogeaskoa@ehu.eus",
      copy: "© 2026 INEDUS · Organised by the Faculty of Education of Bilbao (EHU) and the Faculty of Education and Tourism (FET) of ULEAM",
    },
  },
};

window.CONTENT_EHU = CONTENT_EHU;
